var p=(t,e,o)=>{if(!e.has(t))throw TypeError("Cannot "+o)};var r=(t,e,o)=>(p(t,e,"read from private field"),o?o.call(t):e.get(t)),c=(t,e,o)=>{if(e.has(t))throw TypeError("Cannot add the same private member more than once");e instanceof WeakSet?e.add(t):e.set(t,o)};import"./assets/index-595de9d7.js";import{a as l,N as u,n as h}from"./assets/vendor-83fc1255.js";var i,g,d,y;class m{constructor(){c(this,i,"https://books-backend.p.goit.global/books");c(this,g,"/top-books");c(this,d,"/category-list");c(this,y,"/category?category=")}async getBooks(){return(await l.get(`${r(this,i)}${r(this,g)}`)).data}async getAllCategories(){const e=await l.get(`${r(this,i)}${r(this,d)}`);return console.log(e),e.data}async getBookById(e){return(await l.get(`${r(this,i)}/${e}`)).data}async getBooksFromCategory(e){return(await l.get(`${r(this,i)}${r(this,y)}${e}`)).data}}i=new WeakMap,g=new WeakMap,d=new WeakMap,y=new WeakMap;const k=document.querySelector(".book-block-list");function B(t){return`<li class="book-card" id="${t._id}">
    <div class="book-card-box">
    <img class="book-card-img" src="${t.book_image}" alt="Book cover ${t.title}" loading="lazy" />
    </div>
    <h3 class="book-card-title">${t.title}</h3>
    <p class="book-card-text">${t.author}</p>
    </li>`}function f(t){const e=[];for(let o=0;o<t.length;o+=1){const s=t[o].books.map((n,b)=>{if(b<5)return B(n)}).join(""),a=`<h2 class="best-category-title">${t[o].list_name}</h2>
    <ul class="best-category-list">${s}</ul>
    <div class="see-more-btn-box">
    <button class="see-more-btn" name="${t[o].list_name}" type="button">See more</button></div>`;e.push(a)}k.innerHTML=e.join("")}const $=new m;async function A(){try{const t=await $.getBooks();t.length===0&&u.Notify.warning("Sorry, there are no bestsellers books yet"),f(t)}catch{u.Notify.failure("Something went wrong!")}}A();const w=(t,e)=>{const o=document.createElement("li");o.classList.add("categories-item");const s=`categoryRadio${e+1}`,a=document.createElement("input");a.setAttribute("type","radio"),a.setAttribute("name","category"),a.setAttribute("id",s),a.classList.add("categories-button");const n=document.createElement("label");return n.textContent=t.list_name,n.setAttribute("for",s),n.classList.add("categories-label"),o.appendChild(a),o.appendChild(n),o};async function C(){try{const t=await new m().getAllCategories();t.sort((o,s)=>o.list_name.localeCompare(s.list_name));const e=document.querySelector(".categories-list");t.forEach((o,s)=>{const a=w(o,s);e.appendChild(a)})}catch{h.Notify.failure("Something went wrong!")}}C();
//# sourceMappingURL=commonHelpers.js.map
