var A=(t,o,e)=>{if(!o.has(t))throw TypeError("Cannot "+e)};var c=(t,o,e)=>(A(t,o,"read from private field"),e?e.call(t):o.get(t)),i=(t,o,e)=>{if(o.has(t))throw TypeError("Cannot add the same private member more than once");o instanceof WeakSet?o.add(t):o.set(t,e)};import"./assets/index-8ec8e7ee.js";import{a as d,N as f,n as $}from"./assets/vendor-83fc1255.js";var n,y,m,b;class u{constructor(){i(this,n,"https://books-backend.p.goit.global/books");i(this,y,"/top-books");i(this,m,"/category-list");i(this,b,"/category?category=")}async getBooks(){return(await d.get(`${c(this,n)}${c(this,y)}`)).data}async getAllCategories(){return(await d.get(`${c(this,n)}${c(this,m)}`)).data}async getBookById(o){return(await d.get(`${c(this,n)}/${o}`)).data}async getBooksFromCategory(o){return(await d.get(`${c(this,n)}${c(this,b)}${o}`)).data}}n=new WeakMap,y=new WeakMap,m=new WeakMap,b=new WeakMap;const S=document.querySelector(".book-block-list");function B(t){return`<li class="book-card" id="${t._id}">
    <div class="book-card-box">
    <img class="book-card-img" src="${t.book_image}" alt="Book cover ${t.title}" loading="lazy" />
    </div>
    <h3 class="book-card-title">${t.title}</h3>
    <p class="book-card-text">${t.author}</p>
    </li>`}function _(t){const o=[];for(let e=0;e<t.length;e+=1){const a=t[e].books.map((r,l)=>{if(l<5)return B(r)}).join(""),s=`<h2 class="best-category-title">${t[e].list_name}</h2>
    <ul class="best-category-list">${a}</ul>
    <div class="see-more-btn-box">
    <button class="see-more-btn" name="${t[e].list_name}" type="button">See more</button></div>`;o.push(s)}S.innerHTML=o.join("")}const x=new u;async function L(){try{const t=await x.getBooks();t.length===0&&f.Notify.warning("Sorry, there are no bestsellers books yet"),_(t)}catch{f.Notify.failure("Something went wrong!")}}L();const C=(t,o)=>{const e=document.createElement("li");e.classList.add("categories-item");const a=`categoryRadio${o+1}`,s=document.createElement("input");s.setAttribute("type","radio"),s.setAttribute("name","category"),s.setAttribute("id",a),s.classList.add("categories-button");const r=document.createElement("label");return r.textContent=t.list_name,r.setAttribute("for",a),r.classList.add("categories-label"),e.appendChild(s),e.appendChild(r),e};async function v(){const t=await new u().getAllCategories();t.sort((e,a)=>e.list_name.localeCompare(a.list_name));const o=document.querySelector(".categories-list");t.forEach((e,a)=>{const s=C(e,a);o.appendChild(s)});try{const e=await new u().getAllCategories();e.sort((s,r)=>s.list_name.localeCompare(r.list_name));const a=document.querySelector(".categories-list");e.forEach((s,r)=>{const l=C(s,r);a.appendChild(l)})}catch{$.Notify.failure("Something went wrong!")}}v();const q=new u,g=document.querySelector(".book-block-list"),h=document.querySelector(".book-block-title"),p=document.querySelector(".categories-list");g==null||g.addEventListener("click",T);function T(t){t.preventDefault(),window.scrollTo(window.innerHeight,400),document.querySelectorAll("label").forEach(e=>{e.textContent===t.target.name?e.classList.add("active"):e.classList.remove("active")}),t.target.nodeName==="BUTTON"&&(h.style.display="none",E(t.target.name))}p==null||p.addEventListener("click",I);function I(t){t.preventDefault(),document.querySelectorAll("label").forEach(a=>{a===t.target&&a.classList.add("active"),a.classList.remove("active")});const e=t.target;e.nodeName==="LABEL"&&e.textContent!=="All Categories"?(e.classList.add("active"),h.style.display="none",E(e.textContent)):e.textContent==="All Categories"&&(h.style.display="block",e.classList.add("active"),L())}async function E(t){try{const o=await q.getBooksFromCategory(t);N(o,t)}catch{f.Notify.failure("Sorry, no books in this category")}}function N(t,o){const e=t.map(k=>B(k)).join(""),a=o.split(" ");let s=a.length-1,r=a[s];const w=`<h2 class="book-block-title">${a.splice(0,s).join(" ")}&nbsp;<span class="book-block-title-accent">${r}</span>
    </h2>
    <ul class="category-books-wrapper">${e}</ul>`;g.innerHTML=w,document.querySelectorAll(".book-card").forEach(k=>k.style.display="block")}
//# sourceMappingURL=commonHelpers.js.map
