import './js/shopping-list.js';
import './js/support.js';
import './js/scroll-up.js';
import './js/mobile-menu.js';
import './js/header.js';
import './js/dark-light-switcher.js'
import './js/pagination.js'
import './js/sign-in.js';
import './js/for-authorisation.js';
import './js/firebase.js';